file = open("./testdir/testFile.txt", "r")
content = file.read(3)
file.seek(0)
content1 = file.readline()
content2 = file.readline()
content3 = file.readline()
content4 = file.readline()
nl = "___________________"
print(content)
print(nl)
print(content1)
print(content1.split())
print(nl)
print(content2)
print(nl)
print(content3)
print(content3.isspace())
print(nl)
print(content4)
# print(file.tell())